name = "dylan-portfolio"
compatibility_date = "2025-09-06"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[observability]
enabled = true

[env.preview.assets]
directory = "./dist"
not_found_handling = "single-page-application"

[env.preview]
name = "dylan-portfolio-preview"

[env.preview.observability]
enabled = true
